# Conclusion

As we conclude our brief survey of data visualization, it is clear that the field is rich in potential applications in diverse disciplines, as well as in practical and ethical complexities to be aware of. In the previous chapters, we have presented some important theoretical and practical principles to keep in mind when designing a data visualization. We have also discussed and critiqued several examples of data visualizations, learning common pitfalls and helpful tricks along the way. As we have seen, developing an effective and ethical data visualization is a complex process. The journey from raw data to successful data visualization involves representing the data of interest, processing the data to extract relevant information for the desired argument, designing a mapping of this information to a visual representation, rendering this representation, and combining all this functionality in an easy-to-use product.

**Key Lessons Going Forward:**

* **Don’t try to be too cute.** Using all the fancy features of a visualization tool can lead to complex and confusing graphics. Just because you have a flashy hammer, it does not mean that everything is a nail. Don’t lose your purpose in your infatuation with a new tool or feature. Stick to good design principles, and keep it simple (as was mentioned in the discussion about Patterns).

* **Don’t provide more data than you need to tell your story.** Humans have a tendency to want to create visualizations with multi-drill downs, filters, and tables. This is fine for ad hoc analysis, but if we are presenting a visual with a single story or argument, we must make sure every piece of data included plays a meaningful part in the story.

* **Have more data to show what-ifs.** A great way to provide more information in a visualization is to use filters to provide what-if views. Having filters for different scenarios, options, and time slices provide the user a way to review and discover various perspectives on your data. Just make sure the user does not have to work too hard to get there and that they do not get lost in the data.

* **Deliver value in your visualization.** Many graphs may be aesthetically pleasing or exciting but deliver no value. A graph with good value should deliver important insights to aid decision-making or prompt an action. Keep in mind, the main objective of a visualization is to deliver value, and each design decision should help achieve this.
 
* **Understanding your audience is the most difficult and important part of developing a visualization.** Different audiences will feel differently about the same chart. So when we develop the argument from the data, we should keep our intended audience in mind.

* **Share what you have found.** A visualization can be an effective influencer if used in the correct way and at the correct time. 

## Additional Resources for Aspiring Data Visualizers

The field of data visualization is huge, and the capability of linking storytelling and data-experience design is a commodity. An aspiring visualizer seeking to further broaden his/her knowledge might find these additional resources helpful.

### Tableau Community 

**[@Tableau_Community] helps you to explore Tableau further :** 

* It will help us enhance our learning
* Get answers for most of your doubts In tableau
* Post new questions and crowd source answers
* Attend events, seminars and join conferences conducted locally/ globally
* Give back to the community once you become an expert in that field

**There are very active Tableau social media groups [@LinkedIn_Groups]:**

* Tableau Enthusiasts: LinkedIn Group (19K members)
* Tableau Software Fans & Friends: LinkedIn Group (45k members)


[Describe Artists with Emoji](https://public.tableau.com/en-us/s/gallery/what-emoji-say-about-music?gallery=featured). Using the data from Spotify, the author listed the 10 most distinctive emoji used in the playlists related to popular artists. The table being used in this visual is very straight-forward to link artist to the emojis and is very easy to compare among artists. When you hover over the emoji, further information is presented. 

### Blogs

Here are some blogs recommended by Tableau [@Top_10_Blogs]:

**Blog** | **Description** |
-------- | --------------- |
[Storytelling with Data](http://www.storytellingwithdata.com/) | This blog provides information about the fundamentals of data visualization and how to make data a critical component of your story.|
[Information is Beautiful](https://informationisbeautiful.net/)| This blog was founded by David McCandless, the author of two bestselling infographics books, and provides a variety of visualizations, all of which are continuously revised and updated with the most recent data.|
[Flowing Data](https://flowingdata.com/) | This blog not only provides articles about data viz best practices and charts on a variety of topics, but also offers tutorials and courses for honing the skill of data visualizations|
[Visualizing Data](http://www.visualisingdata.com/) | This blog provides a space for data visualizers to share news and thoughts about the field as well as offers diverse content about current and cutting-edge techniques, discussion of both practical and theoretical topics. |
[Junk Charts](http://junkcharts.typepad.com/) | This blog critiques a variety of graphics, providing insights about what works and what doesn't in each visualization, and how to improve them. |
[The Pudding](https://pudding.cool/) | This blog explores complex and contested issues through visual essays.
[The Atlas](https://www.theatlas.com/) | This blog provides visualizations on a plethora of topics. |
[Graphic Detail](https://www.economist.com/blogs/graphicdetail) | This blog is the hub of The Economist's data journalism; it provides examples of charts, maps, and infographics (all of which are often interactive). |
[Tableau Blog](https://www.tableau.com/about/blog) | The Tableau blog is a source of data viz trends, issues important to the Tableau community, and updates about Tableau products.| 
[Beautiful Data](http://beautifuldata.net/) | This blog features discussion of all things data |
[Data Viz Blog](https://datavizblog.com/) | Michael Sandberg's blog discusses a wide variety of data visualization examples |

### Useful Links on Data Visualization Resources, Trends, and Tutorials

**Resource** | **Description** |
------------------------------|--------------------------------------------------------|
[@charts_viz] | You can find [different types of plots](https://datavizcatalogue.com/search.html) used in data visualization |
[@eagereyes_viz]  |  [Robert Kosara's website](https://eagereyes.org/) which contains recent developments happening in visualization and are likely to have an impact.
[@research_viz]  |  About Robert Kosara and his [research papers](https://research.tableau.com/user/robert-kosara).
[@twitter_Kosara]  |  Robert Kosara's [twitter handle](https://twitter.com/eagereyes?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor).
[@census_viz] | This resource is a data visualization gallery of [weekly explorations of United States Census data](https://www.census.gov/dataviz/) | 
[@fema_viz] | This resource provides a series of [interactive data visualizations using FEMA data](https://www.fema.gov/data-visualization) |
[@7_best_tools] | This [article](https://www.forbes.com/sites/bernardmarr/2017/07/20/the-7-best-data-visualization-tools-in-2017/#3a12b8ea6c30) describes "The 7 Best Data Visualization Tools In 2017" |
[@strategy_impact] | This [article](https://www.iotforall.com/data-visualization-strategy-for-business/) discusses how data visualization can impact business strategy |
[@writers_manipulate] | This [article](https://venngage.com/blog/misleading-graphs/) discusses how writers can use data visualizations to manipulate their audiences |
