# References {-}

### 3.1 Simpson’s Paradox
URL: http://vudlab.com/simpsons/

## Useful Links on Data Visualization Trends, Tutorials and Research Papers

* [@charts_viz] - You can find different types of plots used in data visualization at [Data Catalogue](https://datavizcatalogue.com/search.html).
* [@eagereyes_viz] - Robert Kosara's website which contains recent developments happening in visualization and are likely to have an impact.
* [@research_viz] - About Robert Kosara and his research papers.
* [@twitter_Kosara] - Robert Kosara's twitter handle.
* [@flowingdata] - Website which offers courses, tutorials and happenings in viz. 
* [@infogram] - An infogram helps a user making different types of plots and learning the art of visualization. Engaging infographics, reports, charts, dashboards and maps can be easily created in minutes with it.

## Resources for Aspiring Data Visualists

**2.14 Factors in Computing Systems: Crossings (Vol. 2015-April, pp. 1469-1478). Association for Computing Machinery. DOI: 10.1145/2702123.2702608 (2) Tufte, E. R., and Graves-Morris, P. The visual display of quantitative information, vol. 2. Graphics press Cheshire, CT,1983.**

### Tableau Community 
The following groups or communities help you to explore Tableau further [@Tableau_Community]: 
* It will help us enhance our learning
* Get answers for most of your doubts In tableau
* Post new questions and crowd source answers
* Attend events, seminars and join conferences conducted locally/ globally
* Give back to the community once you become an expert in that field

There are very active Tableau Social Media Groups [@LinkedIn_Groups]:

* Tableau Enthusiasts: LinkedIn Group (19K members)
* Tableau Software Fans & Friends: LinkedIn Group (45k members)

### Blogs
Here is a list of the top 10 blogs that Tableau itself suggests following [@Top_10_Blogs]:

1. Storytelling with Data
2. Information is Beautiful
3. Flowing Data
4. Visualizing Data
5. Junk Charts
6. The Pudding
7. The Atlas
8. Graphic Detail
9. US Census and FEMA
10. Tableau Blog

## Other sources of great visualization

### Tableau: Viz of the Day
Tableau has a gallery called [Viz of the Day](https://public.tableau.com/en-us/s/gallery) that displays great data visualization examples created by Tableau. It is cool to see how people are using all kinds of data to create informative yet fun data visuals. Data being used is also attached so we can try to mimic what other people did as well.  

[Describe Artists with Emoji](https://public.tableau.com/en-us/s/gallery/what-emoji-say-about-music?gallery=featured). Using the data from Spotify, the author listed the 10 most distinctive emoji used in the playlists related to popular artists. The table being used in this visual is very straight forward to link artist to the emojis and is very easy to compare among artists. When you hover over the emoji, further information is presented. 

## More ways to improve your visualization design
### Free eBooks All Designers Should Read

## More ways to improve your visualization design

From online surveys to beefed-up analytics, we’re able to gather and analyze more data than ever before. But how do you turn your findings from a dense spreadsheet into something that really makes your point? Good information design is the key.

There’s a wealth of free resources out there in the form of handy little design ebooks.

* **Design’s Iron Fist** — Jarrod Drysdale

The free ebook, Design’s Iron Fist, is a collection of Drysdale’s previous work all wrapped up in one neat little package. Aside from practical tutorials and processes, this book also offers help on how to get into the mindset of being a truly great designer.

* **The Creative Aid Handbook** — Kooroo Kooroo

Creativity doesn’t just happen overnight. It’s something that each and every designer has to work at on a day-to-day basis. If you find that your innovative juices are running dry, The Creative Aid Handbook could be the answer. The helpful guide looks at how you can boost your intellect, foster your well-being, and, most importantly, become more creative.

* **Designbetter.co** — InVision

InVision released three fantastic design books that are available for free. Each book discusses various aspects of design like design process, management, and business. Moreover, some of the materials are available in audio format.

* **Type Classification**

Type Classification is a helpful beginner’s guide to typography. It should give you the foundations you need to not only start classifying various forms of type but also understanding when and how to use them to alarmingly great effect. It covers a history of each of the type forms and the basic facts you need know about them.[@design_ebooks]

* **Type Classification**

Type Classification is a helpful beginner’s guide to typography. It should give you the foundations you need to not only start classifying various forms of type but also understanding when and how to use them to alarmingly great effect. It covers a history of each of the type forms and the basic facts you need know about them.[@design_ebooks]

## Useful Links on Data Visualization Trends, Tutorials and Research Papers

* [@charts_viz] - You can find different types of plots used in data visualization at [Data Catalogue](https://datavizcatalogue.com/search.html).
* [@eagereyes_viz] - Robert Kosara's website which contains recent developments happening in visualization and are likely to have an impact.
* [@research_viz] - About Robert Kosara and his research papers.
* [@twitter_Kosara] - Robert Kosara's twitter handle.
* [@flowingdata] - Website which offers courses, tutorials and happenings in viz. 
* [@infogram] - An infogram helps a user making different types of plots and learning the art of visualization. Engaging infographics, reports, charts, dashboards and maps can be easily created in minutes with it.

## Resources for Aspiring Data Visualists

### Tableau Community 
The following groups or communities help you to explore Tableau further [@Tableau_Community]: 
* It will help us enhance our learning
* Get answers for most of your doubts In tableau
* Post new questions and crowd source answers
* Attend events, seminars and join conferences conducted locally/ globally
* Give back to the community once you become an expert in that field

There are very active Tableau Social Media Groups [@LinkedIn_Groups]:

* Tableau Enthusiasts: LinkedIn Group (19K members)
* Tableau Software Fans & Friends: LinkedIn Group (45k members)

### Blogs

Here is a list of the top 10 blogs that Tableau itself suggests following [@Top_10_Blogs]:

1. [Storytelling with Data](http://www.storytellingwithdata.com/)
2. [Information is Beautiful](https://informationisbeautiful.net/)
3. [Flowing Data](https://flowingdata.com/)
4. [Visualizing Data](http://www.visualisingdata.com/)
5. [Junk Charts](http://junkcharts.typepad.com/)
6. [The Pudding](https://pudding.cool/)
7. [The Atlas](https://www.theatlas.com/)
8. [Graphic Detail](https://www.economist.com/blogs/graphicdetail)
9. [US Census](https://www.census.gov/dataviz/);[FEMA](https://www.fema.gov/data-visualization)
10. [Tableau Blog](https://www.tableau.com/about/blog)

## Resources for Trends, News, Resources and Opinions of Data Visualization

1. FlowingData: Visualization and Statistics(http://flowingdata.com/)

2. Beautiful Data(http://beautifuldata.net/)

3. Improving data visualisation for the public sector(http://www.improving-visualisation.org/)

4. Michael Sandberg's Data Visualization Blog(https://datavizblog.com/)

