--- 
title: "Patterns"
author: "Zhonghe Han"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This includes tips on how to visualization."
---

#Tips to improve Data Visualization 
1.Comparison

Include a zero baseline if possibleAlthough a line chart does not have to start at a zero baseline, it should be included if it gives more context for comparison. If relatively small fluctuations in data are meaningful (e.g., in stock market data), you may truncate the scale to showcase these variances;
Always choose the most efficient visualization;
Watch your placement
You may have two nice stacked bar charts that are meant to let your reader compare points, but if they’re placed too far apart to “get” the comparison, you’ve already lost;
Tell the whole story
Maybe you had a 30% sales increase in Q4. Exciting! But what’s more exciting? Showing that you’ve actually had a 100% sales increase since Q1.

2.Copy

Don’t over explain
If the copy already mentions a fact, the subhead, callout, and chart header don’t have to reiterate it;
Keep chart and graph headers simple and to the point
There’s no need to get clever, verbose, or pun-tastic. Keep any descriptive text above the chart brief and directly related to the chart underneath. Remember: Focus on the quickest path to comprehension;
Use callouts wisely
Callouts are not there to fill space. They should be used intentionally to highlight relevant information or provide additional context;
Don’t use distracting fonts or elements
Sometimes you do need to emphasize a point. If so, only use bold or italic text to emphasize a point—and don’t use them both at the same time.

3.Color

Use a single color to represent the same type of data;
Watch out for positive and negative numbers
Don’t use red for positive numbers or green for negative numbers. Those color associations are so strong it will automatically flip the meaning in the viewer’s mind;
Make sure there is sufficient contrast between colors;
Avoid patterns
Stripes and polka dots sound fun, but they can be incredibly distracting. If you are trying to differentiate, say, on a map, use different saturations of the same color. On that note, only use solid-colored lines (not dashes);
Select colors appropriately;
Don’t use more than 6 colors in a single layout.

4.Ordering

Order data intuitively
There should be a logical hierarchy. Order categories alphabetically, sequentially, or by value;
Order consistently;
Order evenly
Use natural increments on your axes (0, 5, 10, 15, 20) instead of awkward or uneven increments (0, 3, 5, 16, 50).

5.Audience perspective

Let the users lead;Know your audience,Designers should consider the way users prefer to understand information, even in choosing basic analytic approaches. For users to feel comfortable adopting and sharing insights from analytics, they must be able to explain and defend the data.

6.Use layers to tell a story

While style is one form of customization, layering unique data sets on a single visualization can tell a richer narrative and connect users to the data without getting too crowded. On a map, this can be as simple as zooming in and out, but it can also involve drill-downs (choosing a data point and expanding it to show more detail), links and other shortcuts. 

7.Keep it simple 

Analytic results shouldn’t be presented to 10 decimal places when the user doesn’t need that level of precision to make a decision or understand a concept. Effective visual interfaces avoid 3-D effects or ornate gauge designs (a.k.a. “chart junk”) when simple numbers, maps or graphs will do. 

References: https://www.columnfivemedia.com/25-tips-to-upgrade-your-data-visualization-design 
http://www.govtech.com/pcio/10-Tips-for-Data-Visualization.html
